name: day_24_part2
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  collection: any
  collection_ext: any
  flame: ^1.22.0
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  flame_lint: 1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
